### ISSUE TITLE
Sample workflow file has a mistake

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2524]
Not a major problem since the file is only provided as an example, but see the following:

```
- script: network-layout
  parameters:
    network-type: DH
    allow-looped-networks: false
    consider-only-buildings-with-demand: true
- script: thermal-network
  parameters:
    network-type: DH
    allow-looped-networks: false
    consider-only-buildings-with-demand: true
```

The parameters for `thermal-network` are wrong (there are no `allow-looped-networks` and `consider-only-buildings-with-demand` parameters in the `thermal-network` section of the config file). More meaningful parameters for the thermal network simulation might be `network-model` (simplified or detailed), `network-names`, `substation-cooling-systems`, `substation-heating-systems`, `temperature-control` (VT or CT), `plant-supply-temperature`. Or any other parameter specified in the `thermal-network` section of the config file.

**Comment by martin-mosteiro** [comment]
Perhaps more importantly: `workflow.py` does not seem able to process changes to `thermal_network.network_model`. I set the following in my `.yml` file:
```
- script: thermal-network
  parameters:
    network-type: DH
    network-model: simplified
```
...but I am still getting the detailed model instead.
