### ISSUE TITLE
Archetypes mapper generates unrelated 'Name' values

### ISSUE THREAD

**Issue by MarelloAvanzini** [architecture-building-systems/CityEnergyAnalyst#2722]
**Describe the bug**
I am using CEA to simulate the energy consumption of a neighburhood in Lisbon extracted from a shapefile provided by my thesis supervisor. Using QGIS I managed to cut the neighbourhood, adapt the database structure to fit the new CEA version and export it into a zone file. Then, from it I created my project and a scenario called "Boavista old".
However, when I tried to generate the other input files using 'Archetypes Mapper', all the new table referred to buildings with 'Name' starting from B1000 on, instead of the actual 'Name' retrieved from the zone file (first one being B32540).

**To Reproduce**
1. Go on 'Open Project'
2. Select path of 'Boavista old:
[Boavista old.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4575906/Boavista.old.zip)
3. Go to 'Archetypes Mapper'
4. Scroll down to'buildings', open the selection window and click 'Select all'
5. Click on 'Run Script'
6. Go to 'Input editor'
7. See how the column 'Name' is different from the ones in the other databases (e.g. typology)

**Expected behaviour**
I expect the values in the 'Name' columns to be common to all databases, since otherwise it would not be possible to refer to the actual buildings.

**Screenshots**
![Bug Name](https://user-images.githubusercontent.com/64660466/80990820-4f1f0580-8e37-11ea-9d9f-bc38e5f3792a.PNG)
![Bug typology](https://user-images.githubusercontent.com/64660466/80990831-52b28c80-8e37-11ea-875d-c54c13f45f54.PNG)

**Hardware (please complete the following information):**
 - iOS 10.12 (CEA running on a Windows 10 partition)
 - CEA 3.02

**Note:
I have tried to work around this issue, but I have regularly encountered other errors. Thus I think it is better to solve this one before eventually submitting the others.

**Comment by shanshanhsieh** [comment]
@MarelloAvanzini thank you for submitting this issue, we will take a look at it in the coming sprint.

**Comment by daren-thomas** [comment]
There is a tool `cea rename-buildings` but we just found out that it doesn't work anymore. Maybe this issue could include a fix to it?

**Comment by reyery** [comment]
@MarelloAvanzini the input files that you provided did not include the **typology** file. My suspicion is that the **typology** file that you have used does not have the correct building names as **Archetypes Mapper** creates the other input files based on that.

**Comment by daren-thomas** [comment]
@MarelloAvanzini, based on the scenario you provided (Boavista old) I was not able to reproduce your error - my main question is: Where did your **typology** file come from?

It should be possible to create a typology file in excel - you'll need the following columns (please name them exactly like this):

- Name
- YEAR
- STANDARD
- 1ST_USE
- 1ST_USE_R
- 2ND_USE
- 2ND_USE_R
- 3RD_USE
- 3RD_USE_R
- REFERENCE

add one row for each building in your scenario:

- use "MULTIRES" for the 1ST_USE, 2ND_USE and 3RD_USE - you can change it later in the CEA _before_ running the Archetypes Mapper
- use 1.0 for 1ST_USE_R and 0 for the 2ND_USE_R and 3RD_USE_R
- use STANDARD1 for the STANDARD field
- use an approriate YEAR for the year field
- you can set REFERENCE to "User - input"

Then, run the tool Utilities -> DBF to Excel to DBF to create the typology.dbf file from your typology.xlsx file and place it in `inputs/building-properties`.

You can then edit the typology file and run Archetypes Mapper.

I hope this helps.

**Comment by daren-thomas** [comment]
@MarelloAvanzini, we are closing this issue for now - we can re-open it if the above solution doesn't work.

**Comment by metwaly-ali** [comment]
please what is this ???and how i can make ?
Name
YEAR
STANDARD
1ST_USE
1ST_USE_R
2ND_USE
2ND_USE_R
3RD_USE
3RD_USE_R
REFERENCE

**Comment by reyery** [comment]
@metwaly-ali The glossary of columns can be found in this file:
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/23dc23e23880d9bc358d690a0668758d9731d433/cea/schemas.yml

These columns are created using the zone-helper tool in CEA. You can manually create the file using software like QGIS.
```yaml
get_building_typology:
  created_by:
  - data_migrator
  file_path: inputs/building-properties/typology.dbf
  file_type: dbf
  schema:
    columns:
      Name:
        description: Unique building ID. It must start with a letter.
        type: string
        unit: '[-]'
        values: alphanumeric
      YEAR:
        description: Construction year
        type: int
        unit: '[-]'
        values: '{0...n}'
        min: 0
      STANDARD:
        description: Construction Standard (relates to "code" in Supply Assemblies)
        type: string
        unit: '[-]'
        values: alphanumeric
        choice:
          lookup:
            path: get_database_construction_standards
            sheet: STANDARD_DEFINITION
            column: STANDARD
      1ST_USE:
        description: First (Main) Use type of the building
        type: string
        unit: '[-]'
        values: alphanumeric
        choice:
          lookup:
            path: get_database_use_types_properties
            sheet: INTERNAL_LOADS
            column: code
      1ST_USE_R:
        description: Fraction of gross floor area for first Use Type
        type: float
        unit: '[m2/m2]'
        values: '{0.0...1.0}'
        min: 0.0
        max: 1.0
      2ND_USE:
        description: Second Use type of the building
        type: string
        unit: '[-]'
        values: alphanumeric
        choice:
          lookup:
            path: get_database_use_types_properties
            sheet: INTERNAL_LOADS
            column: code
          none_value: NONE
      2ND_USE_R:
        description: Fraction of gross floor area for second Use Type
        type: float
        unit: '[m2/m2]'
        values: '{0.0...1.0}'
        min: 0.0
        max: 1.0
      3RD_USE:
        description: Third Use type of the building
        type: string
        unit: '[-]'
        values: alphanumeric
        choice:
          lookup:
            path: get_database_use_types_properties
            sheet: INTERNAL_LOADS
            column: code
          none_value: NONE
      3RD_USE_R:
        description: Fraction of gross floor area for third Use Type
        type: float
        unit: '[m2/m2]'
        values: '{0.0...1.0}'
        min: 0.0
        max: 1.0
      REFERENCE:
        description: Reference to data (if any)
        type: string
        unit: '[-]'
        values: alphanumeric
        nullable: true
  used_by:
  - archetypes_mapper
  - demand
  - emissions
```

We have video tutorials on our website (https://www.cityenergyanalyst.com/video-tutorials) that explains how to create building geometries from openstreetmaps, which would generate this file.

Kindly create a new issue if you have encounter any.
