### ISSUE TITLE
Inconsistent/duplicated information in schemas.yml

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2730]
Since we have merged the `glossary.csv` into `schemas.yml`, it introduced a new property `values` which is used to describe the example values found in that column. 

I have realized that numerical types i.e. **int** and **float** are using this property to describe the expected range of the variable.

For example, `1ST_USE_R` expects values between **0.0** and **1.0** based on the property `value`. 
However, this only provides a description for the values but nothing is enforced since ranges for numerical types are enforced with the `min` and `max` property (I don't think we are parsing the string in `values` if I remember correctly).
```
1ST_USE_R:
        description: Fraction of gross floor area for first Use Type
        type: float
        unit: '[m2/m2]'
        values: '{0.0...1.0}'
```
This in turn creates opportunities for inconsistencies in the schema as `values` that do not reflect the range properties.
```
O&M_%:
          description: operation and maintanence cost factor (fraction of the investment
            cost)
          min: 0.0      ^^^ // Should also include `max` property of 100 here
          type: float
          unit: '[%]'
          values: '{0.0...100}' 
```

Because of this duplication of information, we could potentially do away with the `min` and `max` properties and parse `values` instead?
