### ISSUE TITLE
Create Workflow for ReMaP / VILLE

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2861]
To complete the CEA Docker image for ReMaP / VILLE purposes, we need to specify exactly what (and how) the CEA will be used:

- workflow.yml file of the steps
- a definition of the volumes and what inputs to expect (geometry etc.)
- a (small) plugin to send a notification back to the Simulation Server when the workflow is done
  - what is the HOST/PORT?
  - what should be in the message? (we can provide most formats, it's for our consumers to decide)

**Comment by shanshanhsieh** [comment]
1. workflow.yml

```
- config: user
  "general:multiprocessing": False
  "general:project": "${CEA_general_project}/../coverage"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": "heating"
- script: mkdir
  parameters:
    directory: "{general:project}/{general:scenario-name}/inputs/building-geometry"
- script: data-initializer
  parameters:
    databases-path: CH
- script: create-polygon
  parameters:
    # coordinates are kleinalbis, zurich, 4 buildings
    coordinates: "(8.506395769175878, 47.35805575665319), (8.506760549601978, 47.35792978000122), (8.506581736104215, 47.35767782601688), (8.506395769175878, 47.35805575665319)"
    filename: site
- script: zone-helper
- script: surroundings-helper
- script: streets-helper
- script: terrain-helper
- script: weather-helper
  parameters:
    weather: Zuerich-Kloten_1990_2010_TMY
- script: archetypes-mapper
  parameters:
      input-databases: ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules']
      buildings: []
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
```

2. input : 
- list of building coordinates
- weather file (if the user don't have any, we have to use the weather file from our database)

3. return : 
- Bxxx_demand.csv
- Total_demand.csv
(we might have to change the format of these files, this can be defined later)
