### ISSUE TITLE
Generating plots using large amount of buildings takes too long

### ISSUE THREAD

**Issue by Iskenderzeynalov** [architecture-building-systems/CityEnergyAnalyst#3207]
There is a problem with plotting requested graphs. I don't think it's the weakness of my laptop now. I think it is more because of the  software. When I press OK at the end of adding plot it just circles but doesn't give me any plot for 1-2 hours. I didn't try waiting longer for plotting because I didn't know if there will be any result at the end.

P.S. in my simulation there is 45k buildings and all the scripts related to demand and stuff like that is done on the console since it is faster this way. Maybe I can also initiate plotting is console?
![Uploading plotprob.PNG…]()

**Comment by reyery** [comment]
Hi @Iskenderzeynalov, may I know which plots were you trying to generate? 

We have not tested the plotting function of CEA with such a large amount of buildings. But from what I understand, it is more of the limitation of the plotting library that we are using in CEA.

**Comment by Iskenderzeynalov** [comment]
Solar radiation for District (monthly)
Photovoltaic Potential for District (monthly)
Load Curve for District (monthly)

**Comment by Iskenderzeynalov** [comment]
So is it possible to fix this problem? Because I really need the graphs to show in my Master's thesis.

**Comment by Iskenderzeynalov** [comment]
Which plotting library/programming language would you suggest using? Because I will learn it from scratch anyways.

**Comment by reyery** [comment]
I suggest that you can use python (pandas) to read and loop through each csv data file and sum them together in a single file (e.g. another csv). With the new csv, it might be possible to open it in excel and create a graph from that data.

**Comment by Iskenderzeynalov** [comment]
And which columns should I sum up for the 3 graphs that I stated earlier to get for example total.csv? Because there are a lot of columns and I am not sure which ones to sum up and which ones to keep as they are.

Also, what if I will create a csv file called demand_total as it automatically creates in the smaller projects and try to plot my big project again? Can it work? because the csv will be there

**Comment by reyery** [comment]
For **Solar radiation for District (monthly)** you can sum up all the columns with kw in `outputs/solar-radiation/B*_radiation.csv` files to get the radiation for each building. Then resample the data to monthly.

For **Photovoltaic Potential for District (monthly)** you can sum all the columns with kwh in `outputs/potentials/solar/B*_PV.csv` files and resample the data again.

For **Load Curve for District (monthly)**, I am not too familiar with that, but if I am not wrong you can find the required values in the `outputs/demand/B*.csv` files.

I hope this helps.

**Comment by Iskenderzeynalov** [comment]
Hi @reyery ,

I wanted to try to sum all the B* files from demand folder into one total-demand csv, but from my last smaller project I saw that the total_demand scv file has more columns than B* csv file. For example GRID_a0_kW or GRID_l0_kW which I don't know where came from.
[B1000.csv](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/9387434/B1000.csv)
[Total_demand.csv](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/9387435/Total_demand.csv)

I attached my csv files that CEA created for me. 
I wanted to create the same Total_demand file for my bigger project to extract the final data. 
Can You help me with this? Python code would also help me as well. I am just very short on time.

**Comment by reyery** [comment]
If you want the total demand of all buildings, you could just use the Total_demand.csv file, that is created after you run demand, which essentially already sums it up for you. As for the additional columns, below is the glossary of what each column is, you should be able to just extract what you want from the file.

```yaml
get_total_demand:
  created_by:
  - demand
  file_path: outputs/data/demand/Total_demand.csv
  file_type: csv
  float_format: "%.3f"
  schema:
    columns:
      Af_m2:
        description: Conditioned floor area (heated/cooled)
        type: float
        unit: '[m2]'
        values: '{0.0...n}'
        min: 0.0
      Aocc_m2:
        description: Occupied floor area (heated/cooled)
        type: float
        unit: '[m2]'
        values: '{0.0...n}'
        min: 0.0
      Aroof_m2:
        description: Roof area
        type: float
        unit: '[m2]'
        values: '{0.0...n}'
        min: 0.0
      COAL_hs0_kW:
        description: Nominal Coal requirement for space heating supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      COAL_hs_MWhyr:
        description: Coal requirement for space heating supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      COAL_ww0_kW:
        description: Nominal Coal requirement for hotwater supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      COAL_ww_MWhyr:
        description: Coal requirement for hotwater supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      DC_cdata0_kW:
        description: Nominal district cooling for final data center cooling demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      DC_cdata_MWhyr:
        description: District cooling for data center cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      DC_cre0_kW:
        description: Nominal district cooling for refrigeration demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      DC_cre_MWhyr:
        description: District cooling for refrigeration demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      DC_cs0_kW:
        description: Nominal district cooling for space cooling demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      DC_cs_MWhyr:
        description: 'Energy consumption of space cooling system (if supplied by District Cooling), DC_cs = Qcs_sys / eff_cs'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      DH_hs0_kW:
        description: Nominal energy requirement by district heating (space heating
          supply)
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      DH_hs_MWhyr:
        description: Energy requirement by district heating (space heating supply)
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      DH_ww0_kW:
        description: Nominal Energy requirement by district heating (hotwater supply)
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      DH_ww_MWhyr:
        description: Energy requirement by district heating (hotwater supply)
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_cdata0_kW:
        description: Nominal Data centre cooling specific electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_cdata_MWhyr:
        description: Electricity consumption due to data center cooling
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_cre0_kW:
        description: Nominal Refrigeration system electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_cre_MWhyr:
        description: Electricity consumption due to refrigeration
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_cs0_kW:
        description: Nominal Cooling system electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_cs_MWhyr:
        description: 'Energy consumption of cooling system (if supplied by electricity grid), E_cs = Qcs_sys / eff_cs'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_hs0_kW:
        description: Nominal Heating system electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_hs_MWhyr:
        description: Electricity consumption due to space heating
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_sys0_kW:
        description: Nominal end-use electricity demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_sys_MWhyr:
        description: 'End-use total electricity consumption, E_sys =  Eve + Ea + El + Edata + Epro + Eaux + Ev'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      E_ww0_kW:
        description: Nominal Domestic hot water electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      E_ww_MWhyr:
        description: Electricity consumption due to hot water
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Ea0_kW:
        description: Nominal end-use electricity for appliances
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Ea_MWhyr:
        description: End-use electricity for appliances
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Eal0_kW:
        description: Nominal Total net electricity for all sources and sinks.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Eal_MWhyr:
        description: 'End-use electricity consumption of appliances and lighting, Eal = El_W + Ea_W'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Eaux0_kW:
        description: Nominal Auxiliary electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Eaux_MWhyr:
        description: 'End-use auxiliary electricity consumption, Eaux = Eaux_fw + Eaux_ww + Eaux_cs + Eaux_hs + Ehs_lat_aux'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Edata0_kW:
        description: Nominal Data centre electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Edata_MWhyr:
        description: Electricity consumption for data centers
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      El0_kW:
        description: Nominal end-use electricity for lights
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      El_MWhyr:
        description: End-use electricity for lights
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Ev0_kW:
        description: Nominal end-use electricity for electric vehicles
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Ev_MWhyr:
        description: End-use electricity for electric vehicles
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Eve0_kW:
        description: Nominal end-use electricity for ventilation
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Eve_MWhyr:
        description: End-use electricity for ventilation
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Epro0_kW:
        description: Nominal Industrial processes electricity consumption.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Epro_MWhyr:
        description: Electricity supplied to industrial processes
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GFA_m2:
        description: Gross floor area
        type: float
        unit: '[m2]'
        values: '{0.0...n}'
        min: 0.0
      GRID0_kW:
        description: Nominal Grid electricity consumption
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_MWhyr:
        description: 'Grid electricity consumption, GRID_a + GRID_l + GRID_v + GRID_ve + GRID_data + GRID_pro + GRID_aux + GRID_ww + GRID_cs + GRID_hs + GRID_cdata + GRID_cre'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_a0_kW:
        description: Nominal grid electricity requirements for appliances
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_a_MWhyr:
        description: Grid electricity requirements for appliances
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_aux0_kW:
        description: Nominal grid electricity requirements for auxiliary loads
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_aux_MWhyr:
        description: Grid electricity requirements for auxiliary loads
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cdata0_kW:
        description: Nominal grid electricity requirements for servers cooling
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cdata_MWhyr:
        description: Grid electricity requirements for servers cooling
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cre0_kW:
        description: Nominal grid electricity requirements for refrigeration
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cre_MWhyr:
        description: Grid electricity requirements for refrigeration
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cs0_kW:
        description: Nominal grid electricity requirements for space cooling
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_cs_MWhyr:
        description: Grid electricity requirements for space cooling
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_data0_kW:
        description: Nominal grid electricity requirements for servers
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_data_MWhyr:
        description: Grid electricity requirements for servers
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_hs0_kW:
        description: Nominal grid electricity requirements for space heating
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_hs_MWhyr:
        description: Grid electricity requirements for space heating
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_l0_kW:
        description: Nominal grid electricity consumption for lights
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_l_MWhyr:
        description: Grid electricity requirements for lights
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_v0_kW:
        description: Nominal grid electricity consumption for electric vehicles
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_v_MWhyr:
        description: Grid electricity requirements for electric vehicles
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_ve0_kW:
        description: Nominal grid electricity consumption for ventilation
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_ve_MWhyr:
        description: Grid electricity requirements for ventilation
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_pro0_kW:
        description: Nominal grid electricity requirements for industrial processes
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_pro_MWhyr:
        description: Grid electricity requirements for industrial processes
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      GRID_ww0_kW:
        description: Nominal grid electricity requirements for hot water supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      GRID_ww_MWhyr:
        description: Grid electricity requirements for hot water supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      NG_hs0_kW:
        description: Nominal NG requirement for space heating supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      NG_hs_MWhyr:
        description: NG requirement for space heating supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      NG_ww0_kW:
        description: Nominal NG requirement for hotwater supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      NG_ww_MWhyr:
        description: NG requirement for hotwater supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Name:
        description: Unique building ID. It must start with a letter.
        type: string
        unit: 'NA'
        values: alphanumeric
      OIL_hs0_kW:
        description: Nominal OIL requirement for space heating supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      OIL_hs_MWhyr:
        description: OIL requirement for space heating supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      OIL_ww0_kW:
        description: Nominal OIL requirement for hotwater supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      OIL_ww_MWhyr:
        description: OIL requirement for hotwater supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      PV0_kW:
        description: Nominal PV electricity consumption
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      PV_MWhyr:
        description: PV electricity consumption
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      QC_sys0_kW:
        description: Nominal Total system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      QC_sys_MWhyr:
        description: 'Total energy demand for cooling, QC_sys = Qcs_sys + Qcdata_sys + Qcre_sys + Qcpro_sys'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      QH_sys0_kW:
        description: Nominal total building heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      QH_sys_MWhyr:
        description: Total energy demand for heating
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcdata0_kW:
        description: Nominal Data centre cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcdata_MWhyr:
        description: Data centre cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcdata_sys0_kW:
        description: Nominal end-use data center cooling demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcdata_sys_MWhyr:
        description: End-use data center cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcpro_sys0_kW:
        description: Nominal process cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcpro_sys_MWhyr:
        description: Yearly processes cooling demand.
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcre0_kW:
        description: Nominal Refrigeration cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcre_MWhyr:
        description: Refrigeration cooling demand for the system
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcre_sys0_kW:
        description: ' Nominal refrigeration cooling demand'
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcre_sys_MWhyr:
        description: End-use refrigeration demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs0_kW:
        description: Nominal Total cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_MWhyr:
        description: Total cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_dis_ls0_kW:
        description: Nominal Cooling distribution losses.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_dis_ls_MWhyr:
        description: Cooling distribution losses
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_em_ls0_kW:
        description: Nominal Cooling emission losses.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_em_ls_MWhyr:
        description: Cooling emission losses
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_ahu0_kW:
        description: Nominal AHU latent cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_ahu_MWhyr:
        description: AHU latent cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_aru0_kW:
        description: Nominal ARU latent cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_aru_MWhyr:
        description: ARU latent cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_sys0_kW:
        description: Nominal System latent cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_lat_sys_MWhyr:
        description: Latent cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_ahu0_kW:
        description: Nominal AHU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_ahu_MWhyr:
        description: AHU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_aru0_kW:
        description: Nominal ARU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_aru_MWhyr:
        description: ARU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_scu0_kW:
        description: Nominal SCU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_scu_MWhyr:
        description: SCU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_sys0_kW:
        description: Nominal Sensible system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sen_sys_MWhyr:
        description: Sensible system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys0_kW:
        description: Nominal end-use space cooling demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_MWhyr:
        description: 'End-use space cooling demand, Qcs_sys = Qcs_sen_sys + Qcs_lat_sys + Qcs_em_ls + Qcs_dis_ls'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_ahu0_kW:
        description: Nominal AHU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_ahu_MWhyr:
        description: AHU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_aru0_kW:
        description: Nominal ARU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_aru_MWhyr:
        description: ARU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_scu0_kW:
        description: Nominal SCU system cooling demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qcs_sys_scu_MWhyr:
        description: SCU system cooling demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhpro_sys0_kW:
        description: Nominal process heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhpro_sys_MWhyr:
        description: Yearly processes heating demand.
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs0_kW:
        description: Nominal Total heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_MWhyr:
        description: Total heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_dis_ls0_kW:
        description: Nominal Heating system distribution losses.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_dis_ls_MWhyr:
        description: Heating system distribution losses
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_em_ls0_kW:
        description: Nominal Heating emission losses.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_em_ls_MWhyr:
        description: Heating system emission losses
        type: float
        unit: '[MWh/year]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_ahu0_kW:
        description: Nominal AHU latent heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_ahu_MWhyr:
        description: AHU latent heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_aru0_kW:
        description: Nominal ARU latent heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_aru_MWhyr:
        description: ARU latent heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_sys0_kW:
        description: Nominal System latent heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_lat_sys_MWhyr:
        description: System latent heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_ahu0_kW:
        description: Nominal AHU sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_ahu_MWhyr:
        description: Sensible heating demand in AHU
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_aru0_kW:
        description: ARU sensible heating demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_aru_MWhyr:
        description: ARU sensible heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_shu0_kW:
        description: Nominal SHU sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_shu_MWhyr:
        description: SHU sensible heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_sys0_kW:
        description: Nominal HVAC systems sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sen_sys_MWhyr:
        description: Sensible heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys0_kW:
        description: Nominal end-use space heating demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_MWhyr:
        description: 'End-use space heating demand, Qhs_sys = Qhs_sen_sys + Qhs_em_ls + Qhs_dis_ls'
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_ahu0_kW:
        description: Nominal AHU sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_ahu_MWhyr:
        description: AHU system heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_aru0_kW:
        description: Nominal ARU sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_aru_MWhyr:
        description: ARU sensible heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_shu0_kW:
        description: Nominal SHU sensible heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qhs_sys_shu_MWhyr:
        description: SHU sensible heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qww0_kW:
        description: Nominal DHW heating demand.
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qww_MWhyr:
        description: DHW heating demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      Qww_sys0_kW:
        description: Nominal end-use hotwater demand
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      Qww_sys_MWhyr:
        description: End-use hotwater demand
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      SOLAR_hs0_kW:
        description: Nominal solar thermal energy requirement for space heating supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      SOLAR_hs_MWhyr:
        description: Solar thermal energy requirement for space heating supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      SOLAR_ww0_kW:
        description: Nominal solar thermal energy requirement for hotwater supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      SOLAR_ww_MWhyr:
        description: Solar thermal energy requirement for hotwater supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      WOOD_hs0_kW:
        description: Nominal WOOD requirement for space heating supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      WOOD_hs_MWhyr:
        description: WOOD requirement for space heating supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      WOOD_ww0_kW:
        description: Nominal WOOD requirement for hotwater supply
        type: float
        unit: '[kW]'
        values: '{0.0...n}'
        min: 0.0
      WOOD_ww_MWhyr:
        description: WOOD requirement for hotwater supply
        type: float
        unit: '[MWh/yr]'
        values: '{0.0...n}'
        min: 0.0
      people0:
        description: Nominal occupancy
        type: int
        unit: '[people]'
        values: '{0...n}'
        min: 0
  used_by:
  - decentralized
  - emissions
  - network_layout
  - system_costs
  - optimization
  - sewage_potential
  - thermal_network
```
